# Generated by Django 3.1.5 on 2021-02-15 01:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(choices=[('media/profile_pics/Blue.png', 'Blue'), ('media/profile_pics/Green.png', 'Green'), ('media/profile_pics/Purple.png', 'Purple'), ('media/profile_pics/Pink.png', 'Pink'), ('media/profile_pics/Yellow.png', 'Yellow'), ('media/profile_pics/Red.png', 'Red'), ('media/profile_pics/Orange.png', 'Orange')], default='Blue', max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
