# Generated by Django 3.1.5 on 2021-02-15 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.CharField(choices=[('media/profile_pics/Blue.png', 'Blue'), ('media/profile_pics/Green.png', 'Green'), ('media/profile_pics/Purple.png', 'Purple'), ('media/profile_pics/Pink.png', 'Pink'), ('media/profile_pics/Yellow.png', 'Yellow'), ('media/profile_pics/Red.png', 'Red'), ('media/profile_pics/Orange.png', 'Orange')], default='media/profile_pics/Blue.png', max_length=100),
        ),
    ]
