# Generated by Django 3.1.5 on 2023-03-28 02:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CriticProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('critic_name', models.CharField(max_length=100)),
                ('critic_src', models.URLField(max_length=300)),
            ],
            options={
                'unique_together': {('critic_name',)},
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_name', models.CharField(max_length=100)),
                ('release_date', models.DateField()),
                ('platform', models.CharField(choices=[('3DS', '3DS'), ('DS', 'DS'), ('Dreamcast', 'Dreamcast'), ('Game Boy Advance', 'Game Boy Advance'), ('GameCube', 'GameCube'), ('Nintendo 64', 'Nintendo 64'), ('PC', 'PC'), ('PSP', 'PSP'), ('PlayStation 5', 'PlayStation 5'), ('PlayStation 4', 'PlayStation 4'), ('PlayStation 3', 'PlayStation 3'), ('PlayStation 2', 'PlayStation 2'), ('PlayStation', 'PlayStation'), ('PlayStation Vita', 'PlayStation Vita'), ('Stadia', 'Stadia'), ('Switch', 'Switch'), ('Wii U', 'Wii U'), ('Wii', 'Wii'), ('Xbox Series X', 'Xbox Series X'), ('Xbox One', 'Xbox One'), ('Xbox 360', 'Xbox 360'), ('Xbox', 'Xbox')], max_length=100)),
                ('metascore', models.IntegerField()),
                ('image_src', models.URLField(max_length=300)),
                ('game_src', models.URLField(max_length=300)),
            ],
            options={
                'unique_together': {('game_name', 'platform')},
            },
        ),
        migrations.CreateModel(
            name='GameReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_score', models.IntegerField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.game')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('game', 'owner')},
            },
        ),
        migrations.CreateModel(
            name='CriticReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('critic_score', models.IntegerField()),
                ('critic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.criticprofile')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.game')),
            ],
            options={
                'unique_together': {('game', 'critic')},
            },
        ),
    ]
