# Generated by Django 3.1.5 on 2021-02-15 20:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_name', models.CharField(max_length=100)),
                ('release_date', models.DateField()),
                ('platform', models.CharField(max_length=100)),
                ('critic_score', models.IntegerField()),
                ('image_src', models.URLField(max_length=300)),
                ('game_src', models.URLField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='GameReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_name', models.CharField(max_length=100)),
                ('release_date', models.DateField()),
                ('platform', models.CharField(max_length=100)),
                ('critic_score', models.IntegerField()),
                ('image_src', models.URLField(max_length=300)),
                ('game_src', models.URLField(max_length=300)),
                ('user_score', models.IntegerField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
