# Generated by Django 3.1.5 on 2021-03-27 19:18

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='criticprofile',
            unique_together={('critic_name',)},
        ),
        migrations.AlterUniqueTogether(
            name='gamereview',
            unique_together={('game_name', 'platform', 'owner')},
        ),
    ]
